- name: default
  provider: anthropic
  model: claude-3-haiku
  description: Default Claude profile
  temperature: 0.7
  default: true
  system_prompt: |
    You are Claude Squad for Rust, respond succinctly.
  tools:
    - name: http_get
      enabled: false
- name: pro
  provider: openai
  model: gpt-4o
  description: OpenAI profile for advanced usage
  temperature: 0.2
  metadata:
    api_key_env: OPENAI_API_KEY
